spring:
  application:
    name: CUSTOMER-SERVICE

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/farmfresh
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka